export const USER_LOGIN = 'USER_AUTH_CHANGE';
export const USER_LOGOUT = 'USER_LOGOUT';

export const START_LIVE= 'START_LIVE';
export const UPDATE_LIVE_TIME = 'UPDATE_LIVE_TIME';
export const SET_WORKOUT_END_TIME = 'SET_WORKOUT_END_TIME';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const CLEAR_LIVE= 'CLEAR_LIVE';

export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const GET_WORKOUTS = 'GET_WORKOUTS';
export const DELETE_WORKOUT = 'DELETE_WORKOUT';

export const GET_WORKOUT_DETAIL = 'GET_WORKOUT_DETAIL';
export const CLEAR_WORKOUT_DETAIL = 'CLEAR_WORKOUT_DETAIL';

export const SET_WORKOUTS_ORDER = 'SET_WORKOUTS_ORDER';
export const SET_WORKOUTS_FILTERS = 'SET_WORKOUTS_FILTERS';

export const GET_SUMMARY_DATA = 'GET_SUMMARY_DATA';
export const GET_CHART_DATA = 'GET_CHART_DATA';
